#:schema node_modules/wrangler/config-schema.json
name = "smail"
compatibility_date = "2024-09-30"
main = "app/worker.ts"
assets = { directory = "./build/client" }

[observability]
enabled = true

[[kv_namespaces]]
binding = "KV"
id = "9229f90a80604be3ad0d5fc16ef86782"

[[d1_databases]]
binding = "DB"
database_name = "smail"
database_id = "816f4666-3329-4538-952f-8adaa2a09f19"
preview_database_id = "816f4666-3329-4538-952f-8adaa2a09f19"
migrations_dir = "app/drizzle"
